config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"
  resources :users, only: [:show, :edit, :index, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200,}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true
  
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render 'edit'
    end
  end

  def index
    @book = Book.new
    @books = Book.all

  end

  def show
    @bookn = Book.new
    @book = Book.find(params[:id])
    @user = @book.user

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :sign_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
   def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
   end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(id: current_user), notice: 'You have updated user successfully.'
    else
      render "edit"
    end
  end

  def index
    @book = Book.new
    @users = User.all
  end

  private

  def  user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user.id)) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user == current_user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">

<% if book.errors.any? %>
  <%= book.errors.count %>件のエラーが発生しました
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>User info</h1>

<table class="table">
  <tbody>

    <tr><%= image_tag user.get_profile_image(100,100) %></tr>
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
  </tbody>
</table>


<%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block", method: :get do %>
<i class="fas fa-user-cog"></i>
<% end %>

<div>
<h1>New book</h1>
<%= form_with model: book, local:true do |f| %>
 <div>
 <p>Title</p>
 <%= f.text_field :title %>
 </div>
 <div>
 <p>Opinion</p>
 <%= f.text_area :body %>
 </div>
 <%= f.submit "Create Book", class: "btn btn-sm btn-success" %>
<% end %>
</div>

</div>

app/views/books/edit.html.erb
<div class="container">
<div class="row">
<div class="col-mx-auto py-3 offset-md-1">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, method: :patch, local:true do |f| %>
<p>Title</p>
<%= f.text_field :title %>

<p>Opinion</p>
<%= f.text_area :body %>

<div>
<%= f.submit "Update Book", class: "btn btn-sm btn-success" %>
<% end %>
</div>

  <p>
  <%= link_to "Show", book_path(@book.id) %>
  |
  <%= link_to "Back", books_path %>
  </p>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
<div class="row py-3">
<%= render 'books/list', book: @book, user: current_user %>
<div class="col-md-8 offset-md-1">
<h1>Books</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>opinion</th>
    </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id) do %>
         <%= image_tag book.user.get_profile_image(50,50) %>
        <% end %>
        </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    </tr>
  </tbody>
  <% end %>
</table>

</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row py-3">
<%= render 'books/list', book: @bookn, user: @user %>
<div class="col-md-8 offset-md-1">
  <div>
    <h1>Book detail</h1>
  </div>
<table class="table table-striped">
 <tbody>
    <tr class="px-auto">

      <td>
        <%= image_tag @user.get_profile_image(50,50) %><br>
        <%= link_to @user.name, user_path(@user.id) %>
      </td>
      <td><%= link_to @book.title, book_path(@book.id) %></td>
      <td><%= @book.body %></td>
      <% if @user == current_user %>
      <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
      <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
      <% end %>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <diy class="row">

    <h1 class="col-mx-auto py-3 offset-md-1">Welcome to <i class="fas fa-book"></i><strong>Bookers!</h1></strong>

  </div>
</div>

app/views/homes/top.html.erb
<div class="container">

 <div class="row">
  <div class="col-mx-auto col-11 col-sm-10 col-lg-8 col-xl-6 py-3 offset-md-1">
     <h1>Welcome to <i class="fas fa-book"></i>Bookers!!</h1>

     <p>in <span><i class="fas fa-book"></i><strong>Booksers</strong>,</span></p>

     <p>you can share and exchenge your opinions , inpression , and emotions</p>

     <p>about various books!</p>


    <div class="btn-wrapper col-10 mx-auto">
     <div class="row"><%= link_to "Log in", new_user_session_path, class: "btn btn-sm btn-block btn-info mb-3" %></div>
     <div class="row"><%= link_to "Sign up", new_user_registration_path, class: "btn btn-sm btn-block btn-success" %></div>
    </div>
 </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0fe26bc12a.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <div class="container">
       <a class="navbar-brand" href="/">Bookers</a>
       <button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
       data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
       aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
     　</button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
           <% if user_signed_in? %>
           <li class="pr-3">
             <i class="fas fa-home"></i>
             <%= link_to "Home", user_path(id: current_user) %>
           </li>
           <li class="pr-3">
             <i class="fas fa-users"></i>
             <%= link_to "Users", users_path %>
           </li>
            <li class="pr-3">
              <i class="fas fa-book-open"></i>
             <%= link_to "Books", books_path %>
           </li>
           <li class="pr-3">
             <i class="fas fa-sign-out-alt"></i>
             <%= link_to "Log out", destroy_user_session_path, method: :delete %>
           </li>
           <% else %>
           <li class="pr-3">
             <i class="fas fa-home"></i>
             <%= link_to "Home", root_path %>
           </li>
           <li class="pr-3">
             <i class="fas fa-link"></i>
             <%= link_to "About", '/home/about' %>
           </li>
           <li class="pr-3">
             <i class="fas fa-user-plus"></i>
             <%= link_to "Sign up", new_user_registration_path %>
           </li>
           <li class="pr-3">
             <i class="fas fa-sign-in-alt"></i>
             <%= link_to "Log in", new_user_session_path %>
           </li>
           <% end %>
           </ul>
        </div>
      </nav>
    </header>


    <main>
        <%= flash[:notice] %>

      
      <%= yield %>
    </main>

    <footer class="container mt-5">
      <div class="row">
          <div class="mx-auto">
              <p>CopyRight Infratop.inc</p>
          </div>

      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
  <div class="col-mx-auto py-3 offset-md-1">
    <h1>User info</h1>

    <% if @user.errors.any? %>
      <%= @user.errors.count %>errors
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_with model: @user, local:true do |f| %>
<div class="pb-4">
    <p>Name</p>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
</div>

<div class="pb-4">
    <p>Image</p>
    <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
</div>

<div>
    <p>Introduction</p>
    <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介文" %>
</div>

<div>
    <%= f.submit "Update User", class: "btn btn-sm btn-secondary" %>
    <% end %>
</div>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row py-3">
<%= render 'books/list', book: @book, user: current_user %>
<div class="col-md-8 offset-md-1">
<h1>Users</h1>

<div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(50,50) %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row py-3">
<%= render 'books/list', book: @book, user: @user %>

<div class="col-md-8 offset-md-1">
<table class="table table-striped">
  <h1>Books</h1>
  <thead>
    <tr>
      <td></td>
      <td>Title</td>
      <td>Opinion</td>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= link_to image_tag book.user.get_profile_image(50,50) %></td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>